version: "3.8"

services:
  web:
    container_name: next_app
    depends_on:
      - mysqldb
    build: .
    ports:
      - 3000:3000
  mysqldb:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=logger_docker
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=mydbpass
      - MYSQL_ROOT_PASSWORD=mydbpass
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
