version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: logger_docker
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql

  web:
    container_name: next-app
    depends_on:
      - mysqldb
    build: .
    ports:
      - 3000:3000
volumes:
  db:
