import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className="container-md h-100 my-auto">
      <Head>
        <title>Logger with Docker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="row d-flex align-items-center justify-content-center">
        <div className="col h-100 d-flex flex-column align-items-center justify-content-center">
          <span className="display-1 mb-3">📝🐳</span>
          <h1 className="text-center">Welcome to Logger with Docker</h1>
          <p className="text-center">
            This is an example web app/ web service that logs the users request,
            group logs by level, then send them back as a response. This web app
            is containerized using Docker with the SQL and NodeJS as its images.
          </p>
          <Link href="/logs/all">
            <a className="btn btn-primary">See Logs</a>
          </Link>
        </div>
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
